# Generated by Django 2.2 on 2021-07-10 15:57

import app.Utility
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_important', models.BooleanField(db_index=True, default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='rssNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_publisher_name', models.CharField(max_length=128)),
                ('news_publisher_address', models.CharField(max_length=2048)),
                ('description', models.CharField(blank=True, db_index=True, max_length=4096, null=True)),
                ('media', models.CharField(blank=True, db_index=True, max_length=2048, null=True, unique=True)),
                ('guid', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('pub_dt', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('view', models.IntegerField(db_index=True, default=0)),
                ('is_important', models.BooleanField(db_index=True, default=False)),
                ('jalali_pub_dt', models.CharField(default=app.Utility.j_pub_dt, max_length=32)),
                ('check', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
    ]
